### ISSUE TITLE
Resteasy Annotation-Linked Filter Problem

### ISSUE THREAD

**Issue by harrychengchen** [palominolabs/metrics-guice#18]
Hi:

I tried to use this module on a Filter function of Resteasy framework, simple example:

```java

//For simple demonstration purpose  
class UserResource {
  @Post
  public void createUser(){
    return new User();
  }
  
  @Get
  @Auth //Custom annotation, checks user authorization
  public void getUser(int id) {
     return Users.get(id);
  }
}

//...in the linked filter class
@Auth
@Provider
class AuthFilter implements ContainerRequestFilter {
   @Override
   @Timed //Use dropwizard timer
   public void filter(ContainerRequestContext context) throws IOException {
      Users.checkAuth(context);
   }
}

```

AuthFilter will only be invoked when the REST endpoint is annotated with "@Auth" (getUser in this case). 

As soon as I annotated the filter function with @Timed as shown above, the AuthFilter starts to be called on createUser endpoint as well which is not happening when the @Timed annotation is not there.

I'm using io.dropwizard.metrics 3.1.2 and com.palominolabs.metrics 3.1.3.

Thanks!

**Comment by marshallpierce** [comment]
Adding `@Timed` will mean that a subclass of AuthFilter is dynamically generated, which may mess up how Resteasy decides to apply the filter. In particular, the subclass will not have `@Auth`, and I'm guessing that Resteasy does not navigate the class hierarchy.

**Comment by harrychengchen** [comment]
That totally makes sense now. Is there a solution you are aware of?

**Comment by marshallpierce** [comment]
Alas, no. I use Jersey, so I'm not familiar with what tools Resteasy offers. :(

**Comment by harrychengchen** [comment]
I did some research and I found that adding @Inherited to the annotation class is working (kind of): https://github.com/google/guice/issues/201#issuecomment-48215435

However if you have an annotation that you can't have control over, i.e. @Priority, it will not get passed and therefore your filter may be out of order.
