### ISSUE TITLE
Wrong Metrics for Overridden Generic Methods.

### ISSUE THREAD

**Issue by amanhigh** [palominolabs/metrics-guice#21]
Using annotation @Timed on a override method with Generic Parent gives wrong metrics as listner is registered twice and count is exactly double of actual.

Eg.
Sep 26, 2015 10:09:54 AM com.google.inject.internal.ProxyFactory <init>
WARNING: Method [protected void com.aman.netty.handlers.HttpChannelHandler.messageReceived(io.netty.channel.ChannelHandlerContext,java.lang.Object) throws java.lang.Exception] is synthetic and is being intercepted by [com.palominolabs.metrics.guice.TimedInterceptor@bcef303]. This could indicate a bug.  The method may be intercepted twice, or may not be intercepted at all.

where Class in Question is
public class HttpChannelHandler extends SimpleChannelInboundHandler<FullHttpRequest>{
....
@Override
	@Timed
	protected void messageReceived(ChannelHandlerContext ctx, FullHttpRequest request) throws Exception {
....
}
}

This issue is linked to https://github.com/google/guice/issues/640 and should be solved by creating a No Synthetic Matcher.
http://stackoverflow.com/questions/23301694/guice-synthetic-methods-warning

User cannot solve this by overriding Configure Method because Listners are not Publicly Available so something like         
bindListener(Matchers.any(), new TimedListener(metricsRegistry));
can't be done.

**Comment by marshallpierce** [comment]
I'll take a look, thanks!

**Comment by marshallpierce** [comment]
This should be solved by https://github.com/palominolabs/metrics-guice/pull/23.

**Comment by marshallpierce** [comment]
3.1.4 is released; re-open if it's not fixed there.
