### ISSUE TITLE
Can't configure metrics in instance given with Providers or @Provides

### ISSUE THREAD

**Issue by HenriqueMCastro** [palominolabs/metrics-guice#24]
I can't seem to make instances that are binded with toProvider() or with @Provides to work. 
With the @Provider the hear() method in TimedListener (I'm using @Timed) is called with the class of the Provider so it only configures metrics annotations in the Provider itself and not in the provided class.
If I use @Provides to provide the instance then the hear() method in TimedListener is not called.

Am I doing something wrong?

**Comment by marshallpierce** [comment]
The magical timers that apply to `@Timed` can only be inserted when you let Guice handle instantiation so that it can do its AOP.

If you create your instance manually via `@Provides` or a `Provider` class, you're opting out of AOP, so there's no way to do the necessary subclassing.
