### ISSUE TITLE
3.1.4 not found on jcenter

### ISSUE THREAD

**Issue by oGLOWo** [palominolabs/metrics-guice#26]
Hi. I've added the repository to my maven settings, but it still can't resolve metrics-guice. I looked at http://jcenter.bintray.com/com/palominolabs/metrics/ and it's missing. Am I doing something wrong?

**Comment by marshallpierce** [comment]
One quick thing to try - did you try depending on it before you'd set up the jcenter repo? Maven caches download failures but doesn't know how to differentiate failures from different repositories. If so, try deleting your ~/.m2/repository/com/palominolabs and try again.

**Comment by marshallpierce** [comment]
Also, I agree that it's weird that it's not showing up in that link -- the bintray package DOES claim to be linked to jcenter. I'll look into it.

**Comment by marshallpierce** [comment]
It was a bintray issue. The package was linked, but it wasn't showing up so they manually fixed it. Try again and see if it's resolved.

**Comment by oGLOWo** [comment]
Thank you! All good now 👍
