### ISSUE TITLE
Revert license

### ISSUE THREAD

**Issue by benmccann** [palominolabs/metrics-guice#27]
I much preferred the Apache 2 License. It is much more widely used. Would it be possible to switch back the licensing?

**Comment by marshallpierce** [comment]
COIL is strictly *more* permissive than Apache 2. Notably, it doesn't have the restrictions on attribution that AL2 does. I chose the license to be as business friendly as possible. If your legal team has specific objections I'd love to hear about that. I'd consider dual licensing, but I'd also encourage you to prompt your legal team to just read the license (it's short, unlike AL2!) and stop cargo-culting the license approval process. :)

**Comment by benmccann** [comment]
Ok. I got agreement to use it

**Comment by marshallpierce** [comment]
Excellent!
