### ISSUE TITLE
ExceptionMetered not working on abstract class methods

### ISSUE THREAD

**Issue by pratikkumar19** [palominolabs/metrics-guice#28]
I am using Metrics InstrumentationModule to allow Guice to use it as custom injection points.(to allow dropwizard annotation of metrics be applicable on non-resource methods).

But when using the same @ExceptionMetered annotation with @Timed annotation on abstract class methods, only metrics named as @Timed are getting exposed through jmx ports.(@ExceptionMetered is not working)

Is this this the expected behaviour?

**Comment by pratikkumar19** [comment]
@marshallpierce can you help me?

**Comment by marshallpierce** [comment]
@pratikkumar19 Can you provide a test case that fails or some other form of reproduction? Both annotations use the same logic, so I would expect them to behave the same.

**Comment by pratikkumar19** [comment]
I dont have a test case for it . When looking through jconsole , the same method annotated, in the **abstract class** with ,@Timed is exposed via jmx but @EceptionMeterd is not.

**Comment by marshallpierce** [comment]
Is this class hierarchy at least partially Jersey resource classes? If so, which Jersey integration are you using?

**Comment by pratikkumar19** [comment]
No , the abstract class has no class in it's hierarchy which is related to jersey resource.

**Comment by marshallpierce** [comment]
So what you're saying is that you have an abstract class with an abstract method that is annotated with both `@Timed` and `@ExceptionMetered`, and for your various concrete classes that extend the abstract method, only the timer for `@Timed` is showing up, not the exception meter? How are you controlling metric naming for the concrete classes?

**Comment by pratikkumar19** [comment]
Actually the class is abstract , the method is concrete(like template design pattern). The metric naming is done by me i.e some custom metric names for @Timed and @ExceptionMetered. 
Actually the metrics are getting exposed via the abstract class name rather than from the concrete class names.
And also the Exception Metered metric is coming via the super-interface name.
Class Design:
Interface A(exposing @Timed and @exceptionMetered) 
Abstract Class B implements A(exposing @Timed) **[This is the class where I annotated class's "main" method with @Timed and @ExceptionMetered]**
Concrete Class C and D (using super's "main" method , just modifying hooks), no metrics exposed

**Comment by marshallpierce** [comment]
As far as I know, reflection doesn't provide a way to determine what implemented interfaces may provide a method that a specific "class method" is implementing. Thus, we can't tell what interface methods a class method may be related to, so annotations won't work if only placed on the interface.

For methods defined in an abstract class, right now we use `Class#getDeclaredMethods()` to find methods, which will not find superclass methods. It's conceivable that we could switch to using `getMethods()` which does find superclass methods. I'll have to think over if there are non-obvious implications to this. In the meantime, you could override the methods in question, delegate to the superclass's implementation, and annotate the override methods to get the metrics you want.

**Comment by marshallpierce** [comment]
Inactive
