### ISSUE TITLE
Publishing 3.1.4

### ISSUE THREAD

**Issue by roded** [palominolabs/metrics-guice#29]
Hi, 
Can the latest version be publish to a maven repository?
Thanks

**Comment by marshallpierce** [comment]
They are already available in jcenter (specifically, via [this Bintray package](https://bintray.com/marshallpierce/maven/com.palominolabs.metrics%3Ametrics-guice/3.1.4/view#)). There are instructions in the readme for setting up Maven to use jcenter. FYI, jcenter is a superset of maven central, so you do not need to also have maven central if you have jcenter.
