### ISSUE TITLE
No metrics created for classes created by Guice Provider

### ISSUE THREAD

**Issue by vgarmash** [palominolabs/metrics-guice#30]
You need to start using more advanced scenarios in your tests to catch more issues. At this point in your test you use Just-In-Time bindings but this is not the only way to create object in Guice. In some we need to use Provider or method with ```@Provides``` annotation to create objects. 

In my case I had a provider which created instance of the wrapper class for given interface. I had ```@Timed``` annotation on public method of the wrapper which I implemented from the interface.
```
public Interface {
public Object calculate(Object input);
}
...
public class InterfaceWrapper implements Interface {

  @Timed
  @Override
   public Object calculate(Object input) {
     //do something
     return result;
    }
}
...
public MyInterfaceProvider implements Provider<Interface> {
   public Interface get() {
       return new InterfaceWrapper();
    }
}
```

I installed the module like this:
```
install(new MetricsInstrumentationModule(registry));
```

And then I declared my binding like this:

```
bind(Interface.class).to(MyInterfaceProvider.class);
```

When application started I connected to it with JMX Console and there were no Timer metric visible for my ```@Timed``` method. Probably you need another hook to Guice to create metric for objects created by Guice providers.

**Comment by marshallpierce** [comment]
This is not a bug; see Limitations in the README.

**Comment by marshallpierce** [comment]
Oops, I lied -- it's not yet in the readme. It will be momentarily! Short version: Guice AOP can only do its thing if Guice is creating the instance, which it's not here.

**Comment by vgarmash** [comment]
I see... It is actually huge limitation... Providers are really useful for us.

**Comment by marshallpierce** [comment]
That's not how Guice AOP works, so you can either use AOP or providers.
