### ISSUE TITLE
Latest version from Bintray -> Maven Central

### ISSUE THREAD

**Issue by jimhooker2002** [palominolabs/metrics-guice#38]
Hi,

Any chance you could copy/sync the latest version (3.2.1) from Bintray to Maven Central please?

I work for a company with a build system that doesn't know anything about Bintray.  The Jar needs to be in Maven Central for me to be able to consume it.

The following looks super useful in order to achieve this: https://bintray.com/docs/usermanual/uploads/uploads_syncingwiththirdpartyplatforms.html#_syncing_artifacts_with_maven_central

Thanks in advance for any help you can give me here.  Hopefully it should be a quick and easy job to get the Jar synced across.

**Comment by marshallpierce** [comment]
Hi,
Sorry for the delay. Hopefully you were able to start using Bintray in the meantime. ;)

**Comment by marshallpierce** [comment]
I've started a sync for 3.2.1. Hopefully it will show up for you soon in maven central.

**Comment by marshallpierce** [comment]
Naturally it didn't work because Maven Central has a bunch of annoying requirements for useless pom fields. I'll see if I can easily fix that, but no promises... 

(But really, I do hope that you'll be able to use Bintray... It's a superset of Maven Central and generally much nicer to work with.)

**Comment by marshallpierce** [comment]
I released a new version (3.2.2). Bintray thinks [that one syned ok](https://bintray.com/marshallpierce/maven/com.palominolabs.metrics%3Ametrics-guice/3.2.2#central), so keep an eye on https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.palominolabs.metrics%22%20AND%20a%3A%22metrics-guice%22.

**Comment by marshallpierce** [comment]
3.2.2 is now showing up in maven central, so I'm calling this done.
