### ISSUE TITLE
Which is the latest version of the dependency that is compatible with Java 7

### ISSUE THREAD

**Issue by shashank-devisetty** [palominolabs/metrics-guice#39]
I'm using metrics in my application running on Java 7. Which is the latest compatible version?
Is this dependency fine for Java 7

`<dependency>`
`      <groupId>com.palominolabs.metrics</groupId>`
`      <artifactId>metrics-guice</artifactId>`
`      <version>3.2.2</version>`
`      <scope>compile</scope>`
`</dependency>`

**Comment by marshallpierce** [comment]
Looks like 3.2.2 was built to be compatible with java 6, as is the current version. However, Java 7 was EOL'd **over two years ago**. I strongly encourage you to update to Java 8.
