### ISSUE TITLE
Use getMethods instead of getDeclaredMethods?

### ISSUE THREAD

**Issue by jontejj** [palominolabs/metrics-guice#42]
https://github.com/palominolabs/metrics-guice/blob/f46c9fe0363f976155314123686666a8d7e6983b/src/main/java/com/palominolabs/metrics/guice/DeclaredMethodsTypeListener.java#L21

getMethods also return methods in the super class.

**Comment by jontejj** [comment]
I see that https://github.com/google/guice/issues/201 is still open :(

**Comment by marshallpierce** [comment]
Unfortunately, I tried this back in 2015 and gave up. It's more a limitation of the JVM representation of methods. See the chain of commits starting at b2bca7c, summarized in the sad comment at https://github.com/palominolabs/metrics-guice/commit/b0b14f66171ff3928b209b1f870328e0e1ef9e7a#diff-2e878196e8ee792e24b5ca8aef708f26R93. 

There may be a way to do just the right combination of reliably filtering away synthetic methods we don't want, etc, but it's not clear to me what that would be.

**Comment by jontejj** [comment]
I see, shall I leave this issue open?

**Comment by marshallpierce** [comment]
Only if you have an implementation approach :)

**Comment by jontejj** [comment]
Not in the near future :(
